services:
  - type: web
    name: toushi-hanyou
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: toushi-hanyou-db
          property: connectionString

databases:
  - name: toushi-hanyou-db
    databaseName: toushi_hanyou
    user: toushi_hanyou
